services:
  emprius-backend:
    build: .
    ports:
      - "3333:3333"
    depends_on:
      - mongo
    environment:
      - EMPRIUS_MONGO=mongodb://root:emprius@mongo:27017/
      - EMPRIUS_PORT=3333
      - EMPRIUS_DEBUG=true
      - EMPRIUS_REGISTERAUTHTOKEN=comunals
      - WEBAPPDIR=/webapp
    restart: always
    volumes:
      - ./webapp:/webapp

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: emprius

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: emprius
      ME_CONFIG_MONGODB_URL: mongodb://root:emprius@mongo:27017/
    depends_on:
      - mongo

